// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMC6lVnkeIHKGH38C0KSCKAmAwk64n3s',
    appId: '1:412990874478:web:a1b5eb2a5f186aa97d577f',
    messagingSenderId: '412990874478',
    projectId: 'pweench-ca5a3',
    authDomain: 'pweench-ca5a3.firebaseapp.com',
    storageBucket: 'pweench-ca5a3.appspot.com',
    measurementId: 'G-E93TPWQG02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvhL_x16OXWmXkY6l8PD5mIosuIw_N4Q',
    appId: '1:412990874478:android:2322219abeb697637d577f',
    messagingSenderId: '412990874478',
    projectId: 'pweench-ca5a3',
    storageBucket: 'pweench-ca5a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWz-y2rnh63NNVOLzeWCeUw1_xBa_s6_Y',
    appId: '1:412990874478:ios:6fc6c29ea524a9527d577f',
    messagingSenderId: '412990874478',
    projectId: 'pweench-ca5a3',
    storageBucket: 'pweench-ca5a3.appspot.com',
    iosClientId: '412990874478-n6tq5v9ug95592ok94jvilpslbklv2ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.pweench',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWz-y2rnh63NNVOLzeWCeUw1_xBa_s6_Y',
    appId: '1:412990874478:ios:6fc6c29ea524a9527d577f',
    messagingSenderId: '412990874478',
    projectId: 'pweench-ca5a3',
    storageBucket: 'pweench-ca5a3.appspot.com',
    iosClientId: '412990874478-n6tq5v9ug95592ok94jvilpslbklv2ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.pweench',
  );
}
